### ISSUE TITLE
Attention visualization?

### ISSUE THREAD

**Issue by BAILOOL** [JamesChuanggg/san-torch#5]
Is the attention visualization provided?

**Comment by badripatro** [comment]
Hello, 
Please correct me , if i am wrong:
To visualize Attention, Get attention probability and multiply with  32x32 pixel region of  original image.  
 I was trying to return  attention probability  from "attention.lua" file, but facing problem to access that value.
 **Is there is way to access intermediate layers' outputs using nngraph in san-torch code ?**
Please share , If any one has visualized the attention .
